/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CollapseItem: typeof import('./src/components/CollapsePanel/CollapseItem.vue')['default']
    CollapsePanel: typeof import('./src/components/CollapsePanel/index.vue')['default']
    CollapseTransition: typeof import('./src/components/CollapsePanel/CollapseTransition.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    GlobalHeader: typeof import('./src/components/GlobalHeader/GlobalHeader.vue')['default']
    LanguageFilter: typeof import('./src/components/LanguageSelect/LanguageFilter.vue')['default']
    LanguagePopover: typeof import('./src/components/LanguageSelect/LanguagePopover.vue')['default']
    MDialog: typeof import('./src/components/MDialog/MDialog.vue')['default']
    Menus: typeof import('./src/components/GlobalHeader/Menus.vue')['default']
    OrderSteps: typeof import('./src/components/OrderSteps/index.vue')['default']
    QrCode: typeof import('./src/components/QrCode/QrCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleCutterText: typeof import('./src/components/SingleCutterText/index.vue')['default']
    SubMenus: typeof import('./src/components/GlobalHeader/SubMenus.vue')['default']
    UnZip: typeof import('./src/components/UploadFile/model/UnZip.vue')['default']
    UnZipFail: typeof import('./src/components/UploadFile/model/UnZipFail.vue')['default']
    UnZipSuccess: typeof import('./src/components/UploadFile/model/UnZipSuccess.vue')['default']
    UploadFile: typeof import('./src/components/UploadFile/index.vue')['default']
  }
}
